### ISSUE TITLE
nems-migrator version updated to 1.5.1 without updating upgrade.sh

### ISSUE THREAD

**Issue by pickerin** [Cat5TV/nems-migrator#1]
The nems-migrator version was updated to 1.5.1 without updating upgrade.sh
This is resulting in NEMS notifying all users that a 1.5.1 upgrade is available, but upgrade.sh will not upgrade the user to it.

**Comment by Cat5TV** [comment]
Hi @pickerin - the issue is in fact that 1.5.1 is ready but it takes a lot of time for me to port it to each platform. What board are you using? I can prioritize the port as per user request.

nems-upgrade will not get you 1.5.1 as per the release notes on Patreon, which will find their way to the docs once more of the ports are complete. It will be a new build.

Thanks & sorry for the confusion.

**Comment by pickerin** [comment]
Hey Robbie, thanks!  There is a relatively long thread in the Community Forums here about several folks discussing it, I just dug into the root cause:  http://forum.category5.tv/thread-575-page-2.html and opted to bring it to your attention somewhere you probably monitor more often.

I also joined your Patreon, because work like this should be supported.

I'm on an RPI 4 currently.

I saw you did a lot of work to determine the architecture that is running locally, would there be a way to update the ver-current.txt to include architectures it applies to?  That way it wouldn't be updating the MOTD on everyone's system who cannot get the latest version?

**Comment by Cat5TV** [comment]
First @pickerin I _love_ that you dug into it. It's rare for someone to pop by who has actually looked at and understands my code, and I totally respect that - thank you.

Yes, you're bang-on. NEMS was originally Raspberry Pi only. When new ports came along, the ver-current.txt was never enhanced to support multiple platforms (it has never been an issue before since the numerous platforms is a reasonably new expansion). So when I upgraded the Pi version to 1.5.1, it affected the dashboard of all other platforms, but those platforms don't yet have 1.5.1. Catch 22. So, yes: I too was thinking if I moved ver-current.txt to a dynamic method... a variable that is reported for each individual platform, that would resolve this. I think the best way to do this would be to pull the data from the public API (on NEMS Cloud Services) - that way as soon as each platform gets a new version, the version for that platform will be updated. But not before.

Thanks for pointing it out. I knew it was happening in the back of my mind, but it didn't seem like an urgent priority... now that you mention it though, I can see it is more important.

PS - Thank you for your Patronage as well. That means a lot.

Thanks,
Robbie

**Comment by Cat5TV** [comment]
Added to [to-do list](https://docs.nemslinux.com/todo).

**Comment by pickerin** [comment]
Thanks Robbie!  I updated the community forum with this issue.
I'm also a bit confused, since I'm running on a RPI, and it's listed as supported for the 1.5.1 train, why isn't it appearing?  Is the issue that I'm on an RPI4 and that's a different architecture you have to port 1.5.1 to?

**Comment by Cat5TV** [comment]
You must be on NEMS Linux 1.5. The download for RPi has been up a while. Have you downloaded 1.5.1? It is not a rolling release. Let me know.

**Comment by pickerin** [comment]
I guess this is the crux of the issue...

I'm on NEMS 1.5
I run 'nems-upgrade' and it tells me there's no upgrade available.

Do I need to manually download and install NEMS 1.5.1 (that's what you're implying).
If so, does that mean I have to reflash the SD card to get it?

**Comment by Cat5TV** [comment]
Hi @pickerin - this issue has been resolved. As discussed, I wrote the current version into [the platform API](https://nemslinux.com/api/platform/8), and now all boards will report the current version for their platform independently of one another. Thanks again for pointing this out.

PS - In answer to your question, yes, you have to download 1.5.1 and deploy it, if you want to be running 1.5.1. It is not a rolling release, but is available for your RPi 4.
